galaxy_info:
  author: Nishant Parhi
  description: Automation of service manipulation
  min_ansible_version: 2.4
  platforms:
  - name: Fedora
    versions:
    - all

  galaxy_tags: []

dependencies: []